In [5]:
import pandas as pd
import numpy as np

In [6]:
df = pd.read_csv("courier_cleaned_data_2024_2026.csv")

In [7]:
np.random.seed(42)

df["Customer_ID"] = [
    f"CUST{str(i).zfill(4)}"
    for i in np.random.randint(1, 501, size=len(df))
]

df.head()

,Shipment_ID,Order_Date,Delivery_Date,Customer_Type,Origin_Zone,Destination_Zone,Package_Type,Shipping_Mode,Shipping_Cost,Delivery_Days,Delivery_Status,Delivery_Performance,Customer_ID
0,SHP00743,2024-01-01,2024-01-07,Individual,Central,Central,Parcel,Standard,381,6,Delivered,Not On Time,CUST0103
1,SHP00559,2024-01-01,2024-01-04,Individual,Central,East,Parcel,Express,382,3,Delayed,Not On Time,CUST0436
2,SHP00146,2024-01-02,2024-01-06,Individual,North,South,Document,Standard,241,4,Delivered,Not On Time,CUST0349
3,SHP01459,2024-01-02,2024-01-03,Individual,East,North,Fragile,Same Day,412,1,Delivered,On Time,CUST0271
4,SHP01364,2024-01-02,2024-01-04,Individual,East,South,Electronics,Standard,89,2,Delivered,On Time,CUST0107

In [8]:
customers = df[
    ["Customer_ID", "Customer_Type"]
].drop_duplicates()

customers.to_csv("customers.csv", index=False)

customers.head()

  Customer_ID Customer_Type
0    CUST0103    Individual
1    CUST0436    Individual
2    CUST0349    Individual
3    CUST0271    Individual
4    CUST0107    Individual

In [9]:
shipments = df[
    [
        "Shipment_ID",
        "Customer_ID",
        "Order_Date",
        "Delivery_Date",
        "Origin_Zone",
        "Destination_Zone",
        "Package_Type",
        "Shipping_Mode",
        "Shipping_Cost",
        "Delivery_Status",
        "Delivery_Days",
        "Delivery_Performance"
    ]
]

shipments.to_csv("shipments.csv", index=False)

shipments.head()

,Shipment_ID,Customer_ID,Order_Date,Delivery_Date,Origin_Zone,Destination_Zone,Package_Type,Shipping_Mode,Shipping_Cost,Delivery_Status,Delivery_Days,Delivery_Performance
0,SHP00743,CUST0103,2024-01-01,2024-01-07,Central,Central,Parcel,Standard,381,Delivered,6,Not On Time
1,SHP00559,CUST0436,2024-01-01,2024-01-04,Central,East,Parcel,Express,382,Delayed,3,Not On Time
2,SHP00146,CUST0349,2024-01-02,2024-01-06,North,South,Document,Standard,241,Delivered,4,Not On Time
3,SHP01459,CUST0271,2024-01-02,2024-01-03,East,North,Fragile,Same Day,412,Delivered,1,On Time
4,SHP01364,CUST0107,2024-01-02,2024-01-04,East,South,Electronics,Standard,89,Delivered,2,On Time

In [10]:
zones = pd.DataFrame({
    "Zone_ID": ["Z01", "Z02", "Z03", "Z04", "Z05"],
    "Zone_Name": [
        "North",
        "South",
        "East",
        "West",
        "Central"
    ]
})

zones.to_csv("zones.csv", index=False)

zones

  Zone_ID Zone_Name
0     Z01     North
1     Z02     South
2     Z03      East
3     Z04      West
4     Z05   Central